apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen2-oct24-1 
  janus-idp.io/tekton: codegen2-oct24-1
  backstage.io/kubernetes-id: codegen2-oct24-1
  backstage.io/kubernetes-namespace: codegen2-oct24-1 
  app.kubernetes.io/part-of: codegen2-oct24-1
resources: 
- application-dev.yaml